target 'Boss' do
	source 'https://github.com/CocoaPods/Specs.git'
	platform :ios, '8.0'
    
	pod 'AFNetworking'
	pod 'ReactiveCocoa', '2.5'
	pod 'MJExtension'
	pod 'Masonry'
    pod 'MJRefresh'
	pod 'SDWebImage', '~> 3.7.6'
	pod 'STPopup'
	pod 'BaiduMapKit', '~> 3.2'
	pod 'MBProgressHUD', '~> 0.9.1'
	pod 'Reachability', '~> 3.2'
	pod 'MOBFoundation'
	pod 'SIOSocket', '~> 0.2.0'
	pod 'TZImagePickerController'
    pod 'YYText'
    pod 'YYImage'
	pod 'YYCache'
	pod 'CTPersistance', '~> 1.3.5'
	pod 'IQKeyboardManager'

    pod 'SDCycleScrollView','~> 1.64'
    pod 'MLeaksFinder'
    pod 'MWPhotoBrowser'
    pod 'TOCropViewController'
    pod 'DZNEmptyDataSet'
    pod 'JPush'
    pod 'UITableView+FDTemplateLayoutCell', :git => "https://github.com/forkingdog/UITableView-FDTemplateLayoutCell.git", :branch => "master"
    pod 'UICountingLabel','~> 1.2.0'
    pod 'MyLayout'
    pod 'UMengAnalytics'
    pod 'XHLaunchAd'
    pod 'WechatOpenSDK'
   
end
